name: Full Build Pipeline

on:
  push:
    branches: [main, test]
  pull_request:
    branches: [main, test]

jobs:
  backend-build:
    name: Backend Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Maven Compile
        run: mvn clean compile

      - name: Check Backend Code Formatting (Optional)
        run: mvn fmt:check || echo "Lint failed"

  frontend-build:
    name: Frontend Build
    runs-on: ubuntu-latest
    needs: backend-build   # Depende do backend passar
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Cache Node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Dependencies
        run: npm install

      - name: Build React App
        run: npm run build

      - name: Lint Frontend (Optional)
        run: npm run lint || echo "Lint failed"
