name: Deploy

on:
  pull_request:
    branches: ["main", "test"]
  push:
    branches: ["main", "test"]

jobs:
  backend:
    name: Backend Build, Test & Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('backend/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build & Run Tests (Allow Partial Failures)
        working-directory: ./backend
        id: backend-tests
        run: |
          mvn clean test --batch-mode || true
          # Conta total de testes e falhas
          TOTAL=$(find target/surefire-reports -name "*.txt" | xargs cat | grep -c "Tests run")
          FAILURES=$(find target/surefire-reports -name "*.txt" | xargs cat | grep -c "Failures: [1-9]")
          echo "TOTAL=$TOTAL" >> $GITHUB_ENV
          echo "FAILURES=$FAILURES" >> $GITHUB_ENV
          echo "Backend test results: $TOTAL total, $FAILURES failures"

      - name: Set Backend Job Status
        if: always()
        run: |
          PASSED=$((TOTAL - FAILURES))
          if [ $FAILURES -eq 0 ]; then
            echo "Backend tests: all passed ✅"
          elif [ $PASSED -ge $FAILURES ]; then
            echo "Backend tests: partial success ⚠️"
          else
            echo "Backend tests: mostly failed ❌"
            exit 1
          fi

      - name: Run Checkstyle (Quality)
        working-directory: ./backend
        run: mvn checkstyle:checkstyle || echo "Checkstyle violations detected, but pipeline continues"

      - name: Generate JaCoCo Coverage
        working-directory: ./backend
        run: mvn jacoco:report

  frontend:
    name: Frontend Build, Lint & Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Cache Node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('frontend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Dependencies
        working-directory: ./frontend
        run: npm install

      - name: Run Lint
        working-directory: ./frontend
        run: npm run lint

      - name: Run Tests & Coverage (Allow Partial Failures)
        working-directory: ./frontend
        id: frontend-tests
        run: |
          npm test -- --coverage --watchAll=false || true
          TOTAL=$(grep -o "Total: [0-9]\+" coverage-summary.json | awk '{print $2}')
          FAILURES=$(grep -o "Failed: [0-9]\+" coverage-summary.json | awk '{print $2}')
          echo "TOTAL=$TOTAL" >> $GITHUB_ENV
          echo "FAILURES=$FAILURES" >> $GITHUB_ENV
          echo "Frontend test results: $TOTAL total, $FAILURES failures"

      - name: Set Frontend Job Status
        if: always()
        run: |
          PASSED=$((TOTAL - FAILURES))
          if [ $FAILURES -eq 0 ]; then
            echo "Frontend tests: all passed ✅"
          elif [ $PASSED -ge $FAILURES ]; then
            echo "Frontend tests: partial success ⚠️"
          else
            echo "Frontend tests: mostly failed ❌"
            exit 1
          fi

  deploy:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    needs: [backend, frontend]
    if: github.ref == 'refs/heads/main' && success()
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Backend deploy
      - name: Build Backend Docker image
        working-directory: ./backend
        run: |
          docker build -t myapp-backend:latest .

      - name: Push Backend Docker image
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker tag myapp-backend:latest myrepo/myapp-backend:latest
          docker push myrepo/myapp-backend:latest

      # Frontend deploy
      - name: Build Frontend Docker image
        working-directory: ./frontend
        run: |
          docker build -t myapp-frontend:latest .

      - name: Push Frontend Docker image
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker tag myapp-frontend:latest myrepo/myapp-frontend:latest
          docker push myrepo/myapp-frontend:latest

      - name: Deploy to Kubernetes / Server
        run: |
          kubectl apply -f k8s/backend-deployment.yaml
          kubectl apply -f k8s/frontend-deployment.yaml
