name: code quality

on:
  pull_request:
    branches: ["main", "test"]
  push:
    branches: ["main", "test"]

jobs:
  backend-quality:
    name: Backend Quality & Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('backend/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Run Backend Lint & Quality
        working-directory: ./backend
        run: mvn checkstyle:check pmd:check spotbugs:check || echo "Quality warnings detected"

      - name: Generate Backend Coverage
        working-directory: ./backend
        run: mvn jacoco:report

  frontend-quality:
    name: Frontend Quality & Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Cache Node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('frontend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Dependencies
        working-directory: ./frontend
        run: npm install

      - name: Run ESLint
        working-directory: ./frontend
        run: npm run lint || echo "Lint warnings detected"

      - name: Run Frontend Coverage
        working-directory: ./frontend
        run: npm test -- --watchAll=false --coverage
